name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./bc1/pom.xml
          mvn clean package -f ./bc2/pom.xml

      - name: Docker Build and push for Bc1
        uses: docker/build-push-action@v4
        with:
          context: ./bc1
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/bc1:latest
            ghcr.io/${{ github.repository }}/bc1:${{ github.ref_name }}
            
      - name: Docker Build and push for Bc2
        uses: docker/build-push-action@v4
        with:
          context: ./bc2
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/bc2:latest
            ghcr.io/${{ github.repository }}/bc2:${{ github.ref_name }}
            
