---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc1
  labels:
    app: bc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bc1
  template:
    metadata:
      labels:
        app: bc1
    spec:
      containers:
        - name: bc1
          image: username/bc1:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc2
  labels:
    app: bc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bc2
  template:
    metadata:
      labels:
        app: bc2
    spec:
      containers:
        - name: bc2
          image: username/bc2:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: bc1
  labels:
    app: bc1
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bc1


---


apiVersion: v1
kind: Service
metadata:
  name: bc2
  labels:
    app: bc2
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bc2

